yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from .constants import MAX_LEN_TITLE

User = get_user_model()


class Group(models.Model):
    '''
    Создает модель группы

    Atributes:
        title - название группы с ограничением в 200 символов;
        slug - уникальное поле для создания читаемого URL;
        description - описание группы.
    '''

    title = models.CharField(max_length=200, verbose_name='название группы')
    slug = models.SlugField(unique=True, verbose_name='URL')
    description = models.TextField(verbose_name='описание группы')

    class Meta:
        verbose_name = 'группа'
        verbose_name_plural = 'группы'

    def __str__(self) -> str:
        '''Возвращает название группы'''

        return self.title[:MAX_LEN_TITLE]


class Post(models.Model):
    '''
    Создает модель поста

    Atributes:
        text - текст поста;
        pub_date - автоматом создается дата при создании поста;
        author - ключ для связей Many to One;
        group - ключ для связей Many to One;
        image - поле для картинки.
    '''

    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст нового поста',
    )

    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )

    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'
        ordering = ['-pub_date']

    def __str__(self) -> str:
        '''Возвращает название группы'''

        return self.text[:MAX_LEN_TITLE]


class Comment(models.Model):

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        null=True,
        related_name='comments',
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )

    text = models.TextField(
        verbose_name='Текст комментария',
    )

    created = models.DateTimeField(
        auto_created=True,
        auto_now_add=True,
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-created']

    def __str__(self) -> str:
        return self.text[:MAX_LEN_TITLE]


class Follow(models.Model):

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользоваетль'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Подписчик'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'], name='unique'),
        ]
        verbose_name = 'Подписки'
        verbose_name_plural = 'Подписчики'

    def __str__(self) -> str:
        return f'{self.user.username} - {self.author.username}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control'}),
            'group': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

from .models import Post, Group, User, Comment, Follow
from .constants import POSTS_LIMIT
from .forms import PostForm, CommentForm
from .utils import get_page_obj


@cache_page(20, key_prefix='index_page')
def index(request):
    '''Сортирует по дате и возвращает LIMIT обЪектов модели Post'''

    posts = Post.objects.select_related('author')

    context = {
        'page_obj': get_page_obj(request, posts, POSTS_LIMIT),
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    '''
    Проверяет наличие группы.
    возвращает LIMIT обЪектов модели Post
    принадлежащих заданной группе.
    '''

    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()

    context = {
        'page_obj': get_page_obj(request, posts, POSTS_LIMIT),
        'group': group,
    }

    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    '''
    Возвращает посты выбранного автора
    '''

    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=author)

    is_following = False
    if request.user.is_authenticated:
        is_following = Follow.objects.filter(
            user=request.user,
            author=author).exists()

    context = {
        'author': author,
        'page_obj': get_page_obj(request, posts, POSTS_LIMIT),
        'following': is_following
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    '''
    Возвращает выбранный пост.
    Автора поста и колтчесво постов автора
    '''

    post = get_object_or_404(Post, pk=post_id)
    comments = Comment.objects.filter(post=post)
    form = CommentForm(request.POST or None)

    context = {
        'post': post,
        'comments': comments,
        'form': form
    }

    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    '''
    Выводит форму для создания нового поста.
    при валидном заполнении переадресовывает на post_detail.
    добавляет в бд
    '''

    form = PostForm(request.POST or None)

    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()

        return redirect('posts:profile', request.user)

    context = {
        'form': form,
    }

    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    '''
    Возвращает заполненую форму поста автора для редактирования.
    сохраняет изменния в бд.
    изменяет вывод шаблона create_post.html
    '''

    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )

    if request.user != post.author:
        return redirect('posts:post_detail', post_id)

    if form.is_valid():
        form.save()

        return redirect('posts:post_detail', post_id)

    context = {
        'form': form,
        'is_edit': True,
    }

    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):

    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    user = get_object_or_404(User, pk=request.user.id)

    posts = Post.objects.filter(author__following__user=user)

    context = {
        'page_obj': get_page_obj(request, posts, POSTS_LIMIT),
    }

    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    is_subscription = Follow.objects.filter(
        user=request.user,
        author=author).exists()

    if not is_subscription:
        if not request.user.username == username:
            Follow.objects.create(
                user=request.user,
                author=author
            )

    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        user=request.user,
        author__username=username).delete()

    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
{% if is_edit %}
  Редактировать запись
{% else %}
  Добавить запись
{% endif %}
{% endblock %}
{% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Добавить запись
                {% endif %}
              </div>
              <div class="card-body">
                {% include 'includes/form_errors.html' %}
                {% if is_edit %}
                  <form method="post" action="{% url 'posts:post_edit' form.instance.id %}">
                {% else %}
                  <form method="post" action="{% url 'posts:post_create' %}">
                {% endif %}
                {% include 'includes/for_form.html' %}
                  <div class="d-flex justify-content-end">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}
  Подписки
{% endblock %}
  {% block content %}
  <div class="container py-5">
    <h1>Подписки</h1>
    {% include 'posts/includes/switcher.html' with follow=True %}
    {% for post in page_obj %}
      {% include 'posts/includes/post.html' %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    {% include 'posts/includes/post.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
  {% block content %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% include 'posts/includes/switcher.html' with index=True %}
    {% for post in page_obj %}
      {% include 'posts/includes/post.html' %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}
Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
{% load thumbnail %}
<main>
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
        <li class="list-group-item">
          Группа: {{ post.group.title }}
          <a href="{% url 'posts:group' post.group.slug %}">
            <p>все записи группы {{ post.group.title }}</p>
          </a>
        </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span>{{ post.author.posts.count }} </span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaks }}
      </p>
      {% if post.author.username == user.username %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            редактировать запись
          </a>
      {% endif %}
        {% include 'posts/includes/comments.html' %}
    </article>
  </div>
</main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
    <div class="container py-5">
      <div class="mb-5">
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{ page_obj.paginator.count }}</h3>
        <h3>Всего подписок: {{ author.follower.count }}</h3>
        <h3>Всего подписчиков: {{ author.following.count }}</h3>
        {% if request.user.is_authenticated and request.user != author %}
          {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
          {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
          {% endif %}
        {% endif %}
      </div>
      {% for post in page_obj %}
        {% include 'posts/includes/post.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}